### ISSUE TITLE
Convert text to rendered code

### ISSUE THREAD

**Issue by tdivoll** [njlyon0/collab_bilingualism#1]
Super cool website! Very minor, but maybe Pandas in this instance should be `pandas` to stay consistent with `os`?
<img width="1205" alt="image" src="https://github.com/njlyon0/collab_bilingualism/assets/24841909/9eb44ac6-37df-45ed-a735-6cc7b746a9a4">

**Comment by tdivoll** [comment]
It seems like there are several other places that I see the same pattern:
#### Library Loading (Python) 
for each subpage in 
#### Data Wrangling, Visualization, and SQL.

**Comment by njlyon0** [comment]
Thanks for pointing this out!! I'll fix it ASAP

**Comment by njlyon0** [comment]
Okay, I think I found and fixed all of that markdown inconsistency.

Also, per my [contributing guidelines](https://njlyon0.github.io/collab_bilingualism/collabs.html#contributing-overview) I'd say you catching this definitely earns credit as one of the 'bug finders' (see [here](https://njlyon0.github.io/collab_bilingualism/collabs.html#bug-issue-reporting)) so I've added your name and linked your GitHub profile.

Totally happy to link somewhere else (instead of or in addition to) if you'd like that changed or remove you from the site if you'd rather not be tagged in this way. Let me know your preference.

Thanks again for pointing that issue out and I'll leave this issue open for a day so you can weigh in on how/whether you'd like to be mentioned in the contributing credit page!

**Comment by tdivoll** [comment]
Super cool! Thanks for the acknowledgment, it looks great to me. I'd be happy to help with the page if there are definable tasks that need to be taken care of. Like you, I have used R longer, but have used Python/pandas a bit as well and switch between the two often.

**Comment by njlyon0** [comment]
Thank you for catching that mistake! I have a general plan of including a 'spatial data' section in the future but nothing clearly-defined yet. If/when I come up with something I'll definitely reach out!

Also, if you see a sort of 'coding fundamentals' topic that is currently missing I'd love if you pointed it out to me or (if you'd prefer) I can give you access to create the module yourself.
